// Woordenlijsten voor de overhoor-app.
// Nieuwe lijst toevoegen: kopieer een blok en vul word / cls / def in.
// `keys` is optioneel: groepen synoniemen voor het soepel nakijken van de definitie.
// Zonder `keys` haalt de engine de kernwoorden zelf uit de definitie.
// `accept` is optioneel: korte antwoorden die altijd goed zijn.
//
// Twee lestypes:
// 1. Drie delen (Engels): word + cls + def. Beide richtingen, woordsoort erbij.
// 2. Vertaling (Frans): mode "translate", items alleen word + def, één kant op.
//    Meerdere goede vertalingen scheiden met / of komma. Voorbeeld:
//    { id: "frans-unite-1", title: "Frans unité 1", subject: "Frans", mode: "translate",
//      from: "Frans", to: "Nederlands", directions: ["wd"],
//      items: [ { word: "le chien", def: "de hond" }, { word: "manger", def: "eten" } ] }

window.WORDLISTS = [
  {
    id: "horrid-henry-1tto",
    title: "Horrid Henry wordlist",
    subtitle: "1TTO-H/A",
    subject: "Engels",
    classes: ["Verb", "Adjective", "Noun", "Adverb"],
    items: [
      { word: "Glared", cls: "Verb", def: "To look at someone in an angry way.",
        keys: [["look", "stare", "glare"], ["angry", "angrily", "mad", "cross", "anger", "furious"]] },
      { word: "Collided", cls: "Verb", def: "To hit something violently.",
        keys: [["hit", "bump", "crash", "collide", "bang", "smash", "strike"], ["violently", "hard", "violent", "force", "forcefully"]],
        accept: ["crash into", "bump into"] },
      { word: "Sensible", cls: "Adjective", def: "Wise and showing good judgment.",
        keys: [["wise", "smart", "sensible", "reasonable", "clever"], ["judgment", "judgement", "decisions", "choices", "thinking"]] },
      { word: "Guzzle", cls: "Verb", def: "To eat food or drink quickly and in large amounts.",
        keys: [["eat", "drink", "gulp", "swallow", "consume"], ["quickly", "fast", "quick", "rapidly", "greedily", "gobble"], ["large", "lot", "lots", "much", "amounts", "big", "huge"]] },
      { word: "Leap", cls: "Verb", def: "To move suddenly.",
        keys: [["move", "jump", "spring", "bound"], ["suddenly", "sudden", "quickly", "fast"]],
        accept: ["jump"] },
      { word: "Bothered", cls: "Adjective", def: "When something is important to you and you are worried about it.",
        keys: [["important", "matter", "matters", "care", "cares"], ["worried", "worry", "worries", "concerned", "anxious", "upset", "annoyed"]] },
      { word: "Barked", cls: "Verb", def: "To shout at someone in an unfriendly way.",
        keys: [["shout", "yell", "snap", "say", "speak", "scream"], ["unfriendly", "angry", "angrily", "rude", "rudely", "harsh", "harshly", "mean", "unkind", "sharply"]] },
      { word: "Suggested", cls: "Verb", def: "To mention an idea.",
        keys: [["mention", "propose", "offer", "give", "say", "suggest", "recommend"], ["idea", "plan", "thought", "ideas"]] },
      { word: "Roaring", cls: "Adjective", def: "Loud and powerful noise.",
        keys: [["loud", "noisy", "noise", "sound"], ["powerful", "strong", "big", "huge", "deep"]] },
      { word: "Detected", cls: "Verb", def: "To discover something.",
        keys: [["discover", "find", "notice", "spot", "detect", "sense", "see"]] },
      { word: "Gobbled", cls: "Verb", def: "To eat food too fast.",
        keys: [["eat", "ate", "gobble", "swallow"], ["fast", "quickly", "quick", "greedily", "hurry", "rapidly"]] },
      { word: "Trophy", cls: "Noun", def: "A prize that is given to the winner of a competition.",
        keys: [["prize", "cup", "award", "reward"], ["winner", "win", "wins", "winning", "won", "best"], ["competition", "contest", "race", "match", "game", "tournament"]] },
      { word: "Brilliance", cls: "Noun", def: "Being extremely intelligent or skilful.",
        keys: [["intelligent", "smart", "clever", "skilful", "skillful", "skilled", "genius", "talented", "brilliant", "intelligence"], ["extremely", "very", "really", "super"]] },
      { word: "Gleaming", cls: "Adjective", def: "Bright and shiny from being cleaned.",
        keys: [["bright", "shiny", "shine", "shining", "sparkling", "glossy", "polished", "gleam"], ["clean", "cleaned", "cleaning", "polish", "polished", "washed"]] },
      { word: "Trainers", cls: "Noun", def: "Training shoes / sneakers.",
        keys: [["shoes", "sneakers", "trainers", "footwear", "shoe"]],
        accept: ["sneakers", "sport shoes", "sports shoes", "running shoes"] },
      { word: "Frantically", cls: "Adverb", def: "Done in a hurried and chaotic way.",
        keys: [["hurried", "hurry", "fast", "quickly", "rushed", "rushing", "panic", "panicky", "wild", "wildly", "frantic"], ["chaotic", "chaos", "messy", "crazy", "disorganised", "disorganized", "uncontrolled", "panic"]] },
      { word: "Severely", cls: "Adverb", def: "Very seriously.",
        keys: [["seriously", "serious", "severe", "strictly", "harshly", "badly", "strict"], ["very", "really", "extremely"]] },
      { word: "Anxious", cls: "Adjective", def: "Feeling worried and nervous.",
        keys: [["worried", "worry", "worrying", "scared", "afraid", "uneasy"], ["nervous", "nerves", "stressed", "tense", "anxiety"]] },
      { word: "Crept", cls: "Verb", def: "To move slowly, quietly and carefully.",
        keys: [["move", "moved", "walk", "walked", "go", "went", "sneak", "sneaked", "creep", "tiptoe"], ["slowly", "slow"], ["quietly", "quiet", "silently", "silent", "softly"], ["carefully", "careful", "cautiously"]],
        accept: ["sneak", "sneaked", "tiptoe", "tiptoed"] },
      { word: "Sweaty", cls: "Adjective", def: "Covered in sweat.",
        keys: [["sweat", "sweating", "sweaty", "perspiration"]] },
      { word: "Exhausting", cls: "Adjective", def: "Making you feel extremely tired.",
        keys: [["tired", "tiring", "exhausted", "sleepy", "weary"], ["extremely", "very", "really", "super", "totally", "completely"]] },
      { word: "Ancient", cls: "Adjective", def: "From a long time ago / very old.",
        keys: [["old", "ancient", "past", "history", "historic", "antique", "aged"]],
        accept: ["very old", "long ago", "a long time ago"] },
      { word: "Rival", cls: "Noun", def: "A person competing.",
        keys: [["person", "someone", "somebody", "people", "opponent", "competitor", "enemy"], ["competing", "compete", "competition", "against", "beat", "opponent", "competitor", "enemy"]] },
      { word: "Topple", cls: "Verb", def: "To lose balance and fall over.",
        keys: [["fall", "fell", "falls", "falling", "tumble", "collapse"], ["balance", "over", "down"]] },
      { word: "Hesitated", cls: "Verb", def: "To pause before you do or say something.",
        keys: [["pause", "paused", "wait", "waited", "stop", "stopped", "doubt", "doubted", "hesitate", "unsure"], ["before", "saying", "doing", "say", "do", "speak", "act", "decide"]] }
    ]
  },
  {
    id: "frans-arret-apprendre",
    title: "Arrêt Apprendre",
    subtitle: "Vocabulaire & phrases-clés",
    subject: "Frans",
    mode: "translate",
    from: "Frans",
    to: "Nederlands",
    directions: ["wd"],
    sections: { A: "In de klas", B: "Opdrachten", C: "Getallen 1 tot 20", D: "Dagen en huiswerk" },
    items: [
      { section: "A", word: "le français", def: "het Frans" },
      { section: "A", word: "le prof", def: "de docent" },
      { section: "A", word: "l'exercice (m)", def: "de opdracht" },
      { section: "A", word: "oui", def: "ja" },
      { section: "A", word: "non", def: "nee" },
      { section: "A", word: "bonjour", def: "hallo, goedendag" },
      { section: "A", word: "au revoir", def: "tot ziens" },
      { section: "A", word: "très bien", def: "heel goed" },
      { section: "A", word: "merci", def: "bedankt" },
      { section: "A", word: "c'est", def: "het is" },
      { section: "A", word: "Comment tu t'appelles ?", def: "Hoe heet jij?" },
      { section: "A", word: "Je m'appelle Léo.", def: "Ik heet Léo." },
      { section: "A", word: "Je ne sais pas.", def: "Ik weet het niet." },
      { section: "B", word: "écoute", def: "luister" },
      { section: "B", word: "regarde", def: "kijk naar" },
      { section: "B", word: "lis", def: "lees" },
      { section: "B", word: "écris", def: "schrijf" },
      { section: "B", word: "parle", def: "spreek" },
      { section: "B", word: "répète", def: "herhaal" },
      { section: "B", word: "réponds", def: "geef antwoord" },
      { section: "B", word: "le livre", def: "het boek" },
      { section: "B", word: "l'ordinateur (m)", def: "de computer" },
      { section: "B", word: "le stylo", def: "de pen" },
      { section: "B", word: "l'école (v)", def: "de school" },
      { section: "B", word: "prends", def: "pak, neem" },
      { section: "B", word: "ouvre", def: "open" },
      { section: "B", word: "ferme", def: "sluit" },
      { section: "B", word: "cherche", def: "zoek" },
      { section: "B", word: "choisis", def: "kies" },
      { section: "B", word: "C'est quoi ?", def: "Wat is het?" },
      { section: "B", word: "Je ne comprends pas.", def: "Ik begrijp het niet." },
      { section: "B", word: "Prends le livre.", def: "Pak het boek." },
      { section: "C", word: "un", def: "één / een" },
      { section: "C", word: "deux", def: "twee" },
      { section: "C", word: "trois", def: "drie" },
      { section: "C", word: "quatre", def: "vier" },
      { section: "C", word: "cinq", def: "vijf" },
      { section: "C", word: "six", def: "zes" },
      { section: "C", word: "sept", def: "zeven" },
      { section: "C", word: "huit", def: "acht" },
      { section: "C", word: "neuf", def: "negen" },
      { section: "C", word: "dix", def: "tien" },
      { section: "C", word: "onze", def: "elf" },
      { section: "C", word: "douze", def: "twaalf" },
      { section: "C", word: "treize", def: "dertien" },
      { section: "C", word: "quatorze", def: "veertien" },
      { section: "C", word: "quinze", def: "vijftien" },
      { section: "C", word: "seize", def: "zestien" },
      { section: "C", word: "dix-sept", def: "zeventien" },
      { section: "C", word: "dix-huit", def: "achttien" },
      { section: "C", word: "dix-neuf", def: "negentien" },
      { section: "C", word: "vingt", def: "twintig" },
      { section: "D", word: "lundi", def: "maandag" },
      { section: "D", word: "mardi", def: "dinsdag" },
      { section: "D", word: "mercredi", def: "woensdag" },
      { section: "D", word: "jeudi", def: "donderdag" },
      { section: "D", word: "vendredi", def: "vrijdag" },
      { section: "D", word: "samedi", def: "zaterdag" },
      { section: "D", word: "dimanche", def: "zondag" },
      { section: "D", word: "aujourd'hui", def: "vandaag" },
      { section: "D", word: "apprends", def: "leer" },
      { section: "D", word: "fais", def: "doe / maak" },
      { section: "D", word: "travaille", def: "werk" },
      { section: "D", word: "complète", def: "vul in / vul aan" },
      { section: "D", word: "les devoirs", def: "het huiswerk" },
      { section: "D", word: "le garçon", def: "de jongen" },
      { section: "D", word: "la fille", def: "het meisje" },
      { section: "D", word: "la page", def: "de bladzijde" },
      { section: "D", word: "le mot", def: "het woord" },
      { section: "D", word: "On a des devoirs ?", def: "Hebben we huiswerk?" }
    ]
  }
];
