// Woordenlijsten voor de overhoor-app.
// Nieuwe lijst toevoegen: kopieer een blok en vul word / cls / def in.
// `keys` is optioneel: groepen synoniemen voor het soepel nakijken van de definitie.
// Zonder `keys` haalt de engine de kernwoorden zelf uit de definitie.
// `accept` is optioneel: korte antwoorden die altijd goed zijn.
//
// Twee lestypes:
// 1. Drie delen (Engels): word + cls + def. Beide richtingen, woordsoort erbij.
// 2. Vertaling (Frans): mode "translate", items alleen word + def, één kant op.
//    Meerdere goede vertalingen scheiden met / of komma. Voorbeeld:
//    { id: "frans-unite-1", title: "Frans unité 1", subject: "Frans", mode: "translate",
//      from: "Frans", to: "Nederlands", directions: ["wd"],
//      items: [ { word: "le chien", def: "de hond" }, { word: "manger", def: "eten" } ] }

window.WORDLISTS = [
  {
    id: "gold-a2-starter-unit1",
    title: "Wordlist starter + unit 1",
    subtitle: "Gold Experience A2",
    subject: "Engels",
    classes: ["Noun", "Verb", "Adjective", "Phrase", "Phrasal verb", "Collocation"],
    items: [
      { word: "amazing", cls: "Adjective", def: "very good, especially in an unexpected way",
        keys: [["good", "great", "nice", "excellent", "brilliant", "amazing", "awesome", "fantastic"], ["unexpected"]] },
      { word: "aunt(y)", cls: "Noun", def: "the sister of your father or mother, or the wife of your father’s or mother’s brother",
        keys: [["sister"], ["father", "dad", "daddy", "parent"], ["mother", "mum", "mom", "mummy", "parent"]] },
      { word: "author", cls: "Noun", def: "a person who writes books",
        keys: [["write", "writing", "written", "writes"], ["book", "books"]] },
      { word: "awesome", cls: "Adjective", def: "very good",
        accept: ["very good", "great", "excellent", "amazing", "really good", "cool", "fantastic"] },
      { word: "bake", cls: "Verb", def: "to cook something using dry heat, in an oven",
        keys: [["cook", "cooking", "bake", "baking", "oven"], ["heat"], ["cook", "cooking", "bake", "baking", "oven"]] },
      { word: "baking", cls: "Noun", def: "the activity or process of cooking food using dry heat, typically inside an oven",
        keys: [["activity"], ["process"], ["cook", "cooking", "bake", "baking", "oven"]] },
      { word: "be into something", cls: "Phrase", def: "to like and be interested in something" },
      { word: "beautiful", cls: "Adjective", def: "extremely attractive to look at",
        keys: [["extremely"], ["attractive"], ["look", "looking", "see", "seeing", "watch", "find"]] },
      { word: "belong", cls: "Verb", def: "to be a member of a group or organization",
        keys: [["member"], ["group", "team", "club", "organization", "organisation"], ["group", "team", "club", "organization", "organisation"]] },
      { word: "bookcase", cls: "Noun", def: "a piece of furniture with shelves to hold books",
        keys: [["piece"], ["furniture"], ["shelf", "shelves"]] },
      { word: "brilliant", cls: "Adjective", def: "excellent",
        accept: ["excellent", "very good", "great", "amazing", "fantastic", "really good"] },
      { word: "busy", cls: "Adjective", def: "if you are busy, you are working hard and have a lot of things to do",
        keys: [["work", "working", "works", "job"], ["hard"]] },
      { word: "camping", cls: "Noun", def: "the holiday activity of living in a tent",
        keys: [["holiday"], ["activity"], ["living"]] },
      { word: "campsite", cls: "Noun", def: "an area where people can camp",
        keys: [["room", "building", "place", "area"], ["camp"]] },
      { word: "Can you say that again, please?", cls: "Phrase", def: "used to ask someone to repeat what they have just said",
        keys: [["repeat"], ["just"], ["said"]] },
      { word: "care about sth", cls: "Collocation", def: "thinking about something with your heart or mind because it's important to you",
        keys: [["thinking"], ["heart"], ["mind"]] },
      { word: "catch", cls: "Verb", def: "to trap an animal or fish by using a trap, net, or hook, or by hunting it",
        keys: [["trap"], ["animal"], ["fish"]] },
      { word: "catch a bus or….", cls: "Phrase", def: "To get on or travel on a type of public transportation",
        keys: [["travel"], ["type"], ["public"]] },
      { word: "catch a cold", cls: "Phrase", def: "To get sick with a common cold or minor illness",
        keys: [["sick"], ["common"], ["minor"]] },
      { word: "catch up", cls: "Phrasal verb", def: "To talk with a friend you haven't seen in a while to share news. / To move faster to reach someone ahead of you, or do extra work to finish late tasks.",
        keys: [["speak", "speaking", "say", "saying", "talk", "talking", "tell", "ask"], ["friend"], ["havent"]] },
      { word: "catch your breath", cls: "Phrase", def: "To stop and breathe normally again after running, exercising, or working hard.",
        keys: [["stop"], ["breathe"], ["normally"]] },
      { word: "common", cls: "Adjective", def: "Happening often / Usual",
        keys: [["happening"], ["usual"]] },
      { word: "competition", cls: "Noun", def: "an organised event in which people or teams compete against each other",
        keys: [["organised"], ["event"], ["group", "team", "club", "organization", "organisation", "teams"]] },
      { word: "complete", cls: "Verb", def: "to write the information that is needed on a form",
        keys: [["write", "writing", "written", "writes"], ["information"], ["needed"]] },
      { word: "cousin", cls: "Noun", def: "the child of your uncle and/or aunt",
        keys: [["child", "kid", "son", "daughter"], ["uncle"], ["aunt"]] },
      { word: "cupboard", cls: "Noun", def: "a piece of furniture with doors, and sometimes shelves, used for storing things",
        keys: [["piece"], ["furniture"], ["doors"]] },
      { word: "cushion", cls: "Noun", def: "a cloth bag filled with soft material that you put on a chair or the floor to make it more comfortable",
        keys: [["clothes", "clothing", "cloth", "wear", "wearing"], ["filled"], ["soft"]] },
      { word: "date of birth", cls: "Phrase", def: "the day and year when someone was born",
        keys: [["year"], ["born"]] },
      { word: "dictionary", cls: "Noun", def: "a book that gives a list of words and their meanings",
        keys: [["book", "books"], ["gives"], ["list"]] },
      { word: "double", cls: "Adjective", def: "used to say that a particular letter or number is repeated",
        keys: [["letter"], ["number"], ["repeated"]] },
      { word: "drawing", cls: "Noun", def: "the art or skill of making pictures, plans, etc. with a pen or pencil",
        keys: [["skill"], ["making"], ["pictures"]] },
      { word: "earn money", cls: "Collocation", def: "to receive a particular amount of money for the work that you do",
        keys: [["receive"], ["amount"], ["work", "working", "works", "job"]] },
      { word: "first name", cls: "Noun", def: "the name or names that come before your family name",
        keys: [["come"], ["family"]] },
      { word: "free time", cls: "Collocation", def: "time when you have no work, and nothing else that you must do",
        keys: [["work", "working", "works", "job"], ["nothing"], ["else"]] },
      { word: "grandparents (pl)", cls: "Noun", def: "the parents of a mother or a father",
        keys: [["father", "dad", "daddy", "parent", "parents"], ["mother", "mum", "mom", "mummy", "parent"], ["father", "dad", "daddy", "parent"]] },
      { word: "hang out", cls: "Phrasal verb", def: "to spend a lot of time in a particular place or with particular people",
        keys: [["spend"], ["time", "times"], ["room", "building", "place", "area"]] },
      { word: "Here you are", cls: "Phrase", def: "used when you are giving something to someone",
        accept: ["giving something to someone", "when you give something", "here it is", "take it"] },
      { word: "in a minute", cls: "Phrase", def: "very soon",
        accept: ["very soon", "soon", "in a moment", "right away", "quickly"] },
      { word: "language", cls: "Noun", def: "a system of communication, which is used by the people of a particular country or area",
        keys: [["system"], ["communication"], ["country"]] },
      { word: "library", cls: "Noun", def: "a room or building containing books that can be looked at or borrowed",
        keys: [["room", "building", "place", "area"], ["room", "building", "place", "area"], ["containing"]] },
      { word: "look (it) up", cls: "Phrasal verb", def: "if you look up information in a book, on a computer, etc., you try to find it there",
        keys: [["information"], ["book", "books"], ["computer"]] },
      { word: "match", cls: "Noun", def: "A organized game between two people or teams.",
        keys: [["organized"], ["game", "match", "sport"], ["group", "team", "club", "organization", "organisation", "teams"]] },
      { word: "match", cls: "Verb", def: "to put two people or things together that are similar to or somehow connected with each other",
        keys: [["together"], ["similar"], ["somehow"]] },
      { word: "mean", cls: "Verb", def: "To know what the message is or something refers to.",
        keys: [["know"], ["message"], ["refers"]] },
      { word: "mean", cls: "Adjective", def: "unkind, for example by not letting somebody have or do something / not willing to give or share things, especially money",
        keys: [["unkind"], ["letting"], ["willing"]] },
      { word: "Miss", cls: "Noun", def: "used in front of the family name of a woman who is not married to be politely",
        keys: [["front"], ["family"], ["name", "names", "called"]] },
      { word: "Mr", cls: "Noun", def: "used before a man’s family name to be polite",
        keys: [["mans"], ["family"], ["name", "names", "called"]] },
      { word: "Mrs", cls: "Noun", def: "used before a married woman’s family name to be polite",
        keys: [["married", "marry", "marriage", "wife", "husband"], ["womans"], ["family"]] },
      { word: "Ms", cls: "Noun", def: "used before a woman’s family name when she does not want to be called ‘Mrs’ or ‘Miss’",
        keys: [["womans"], ["family"], ["name", "names", "called"]] },
      { word: "nationality", cls: "Noun", def: "the state of being legally a citizen of a particular country",
        keys: [["state"], ["being"], ["legally"]] },
      { word: "noticeboard", cls: "Noun", def: "a special board on a wall which information can be added",
        keys: [["special"], ["board"], ["wall"]] },
      { word: "novel", cls: "Noun", def: "a story long enough to fill a complete book, in which the characters and events are mostly imaginary",
        keys: [["story", "stories", "tale"], ["long"], ["enough"]] },
      { word: "of course", cls: "Phrase", def: "used to emphasize that you are saying yes when someone asks your permission to do something",
        keys: [["emphasize"], ["speak", "speaking", "say", "saying", "talk", "talking", "tell", "ask"], ["speak", "speaking", "say", "saying", "talk", "talking", "tell", "ask", "asks"]] },
      { word: "pass", cls: "Verb", def: "to hold something in your hand and give it to someone else",
        keys: [["hold", "holding", "keep", "keeping", "store", "storing", "put", "putting"], ["hand"], ["give"]] },
      { word: "practice", cls: "Noun", def: "the thing you do or the time you spend doing an activity to get better",
        keys: [["time", "times"], ["spend"], ["doing"]] },
      { word: "practise", cls: "Verb", def: "to do an activity repeatedly to get better at it",
        keys: [["activity"], ["repeatedly"], ["better"]] },
      { word: "put (your hand) up", cls: "Phrasal verb", def: "to raise (a hand) to a higher position",
        keys: [["raise"], ["higher"], ["position"]] },
      { word: "reading", cls: "Noun", def: "the activity or skill of understanding written words",
        keys: [["activity"], ["skill"], ["understanding"]] },
      { word: "repeat", cls: "Verb", def: "to say or write something again",
        keys: [["write", "writing", "written", "writes"], ["again"]] },
      { word: "shelf", cls: "Noun", def: "a long flat narrow board attached to a wall or in a frame or cupboard, used for putting things on",
        keys: [["long"], ["flat"], ["narrow"]] },
      { word: "signature", cls: "Noun", def: "your name written in special handwriting—often quickly or with letters connected together.",
        keys: [["name", "names", "called"], ["write", "writing", "written", "writes"], ["special"]] },
      { word: "socks (pl)", cls: "Noun", def: "pieces of clothing that you wear on your feet inside your shoes",
        keys: [["pieces"], ["clothes", "clothing", "cloth", "wear", "wearing"], ["clothes", "clothing", "cloth", "wear", "wearing"]] },
      { word: "spend time", cls: "Collocation", def: "to do something or be somewhere for a certain time",
        keys: [["somewhere"], ["certain"]] },
      { word: "surname / family name", cls: "Noun", def: "the name that you share with your parents or and which comes at the end of your full name",
        keys: [["share"], ["father", "dad", "daddy", "parent", "parents"], ["comes"]] },
      { word: "take a photo", cls: "Collocation", def: "to use a camera or phone to get a picture of something",
        keys: [["camera"], ["phone"], ["picture"]] },
      { word: "towel", cls: "Noun", def: "a piece of cloth that you use for drying your skin",
        keys: [["piece"], ["clothes", "clothing", "cloth", "wear", "wearing"], ["drying"]] },
      { word: "turn to", cls: "Phrasal verb", def: "to look at a particular page in a book, magazine, etc.",
        keys: [["look", "looking", "see", "seeing", "watch", "find"], ["page"], ["book", "books"]] },
      { word: "uncle", cls: "Noun", def: "the brother of your mother or father, or the husband of your aunt",
        keys: [["brother"], ["mother", "mum", "mom", "mummy", "parent"], ["father", "dad", "daddy", "parent"]] },
      { word: "valid", cls: "Adjective", def: "a valid ticket, document, or agreement is legally or officially acceptable",
        keys: [["ticket"], ["document"], ["agreement"]] },
      { word: "wardrobe", cls: "Noun", def: "a large piece of furniture that you hang clothes in",
        keys: [["large"], ["piece"], ["furniture"]] },
      { word: "well done", cls: "Phrase", def: "used to praise someone when you think they have done something very well",
        keys: [["praise"], ["think"]] },
      { word: "well-done", cls: "Adjective", def: "food cooked completely or for a long time",
        keys: [["food"], ["cook", "cooking", "bake", "baking", "oven", "cooked"], ["completely"]] },
      { word: "work in pairs", cls: "Phrase", def: "to work in groups of two",
        accept: ["in groups of two", "with two people", "in twos", "with a partner", "two people together"] },
    ]
  },
  {
    id: "horrid-henry-1tto",
    title: "Horrid Henry wordlist",
    deadline: "2026-09-17",   // datum van de overhoring
    subject: "Engels",
    classes: ["Verb", "Adjective", "Noun", "Adverb"],
    items: [
      { word: "Glared", cls: "Verb", def: "To look at someone in an angry way.",
        keys: [["look", "stare", "glare"], ["angry", "angrily", "mad", "cross", "anger", "furious"]] },
      { word: "Collided", cls: "Verb", def: "To hit something violently.",
        keys: [["hit", "bump", "crash", "collide", "bang", "smash", "strike"], ["violently", "hard", "violent", "force", "forcefully"]],
        accept: ["crash into", "bump into"] },
      { word: "Sensible", cls: "Adjective", def: "Wise and showing good judgment.",
        keys: [["wise", "smart", "sensible", "reasonable", "clever"], ["judgment", "judgement", "decisions", "choices", "thinking"]] },
      { word: "Guzzle", cls: "Verb", def: "To eat food or drink quickly and in large amounts.",
        keys: [["eat", "drink", "gulp", "swallow", "consume"], ["quickly", "fast", "quick", "rapidly", "greedily", "gobble"], ["large", "lot", "lots", "much", "amounts", "big", "huge"]] },
      { word: "Leap", cls: "Verb", def: "To move suddenly.",
        keys: [["move", "jump", "spring", "bound"], ["suddenly", "sudden", "quickly", "fast"]],
        accept: ["jump"] },
      { word: "Bothered", cls: "Adjective", def: "When something is important to you and you are worried about it.",
        keys: [["important", "matter", "matters", "care", "cares"], ["worried", "worry", "worries", "concerned", "anxious", "upset", "annoyed"]] },
      { word: "Barked", cls: "Verb", def: "To shout at someone in an unfriendly way.",
        keys: [["shout", "yell", "snap", "say", "speak", "scream"], ["unfriendly", "angry", "angrily", "rude", "rudely", "harsh", "harshly", "mean", "unkind", "sharply"]] },
      { word: "Suggested", cls: "Verb", def: "To mention an idea.",
        keys: [["mention", "propose", "offer", "give", "say", "suggest", "recommend"], ["idea", "plan", "thought", "ideas"]] },
      { word: "Roaring", cls: "Adjective", def: "Loud and powerful noise.",
        keys: [["loud", "noisy", "noise", "sound"], ["powerful", "strong", "big", "huge", "deep"]] },
      { word: "Detected", cls: "Verb", def: "To discover something.",
        keys: [["discover", "find", "notice", "spot", "detect", "sense", "see"]] },
      { word: "Gobbled", cls: "Verb", def: "To eat food too fast.",
        keys: [["eat", "ate", "gobble", "swallow"], ["fast", "quickly", "quick", "greedily", "hurry", "rapidly"]] },
      { word: "Trophy", cls: "Noun", def: "A prize that is given to the winner of a competition.",
        keys: [["prize", "cup", "award", "reward"], ["winner", "win", "wins", "winning", "won", "best"], ["competition", "contest", "race", "match", "game", "tournament"]] },
      { word: "Brilliance", cls: "Noun", def: "Being extremely intelligent or skilful.",
        keys: [["intelligent", "smart", "clever", "skilful", "skillful", "skilled", "genius", "talented", "brilliant", "intelligence"], ["extremely", "very", "really", "super"]] },
      { word: "Gleaming", cls: "Adjective", def: "Bright and shiny from being cleaned.",
        keys: [["bright", "shiny", "shine", "shining", "sparkling", "glossy", "polished", "gleam"], ["clean", "cleaned", "cleaning", "polish", "polished", "washed"]] },
      { word: "Trainers", cls: "Noun", def: "Training shoes / sneakers.",
        keys: [["shoes", "sneakers", "trainers", "footwear", "shoe"]],
        accept: ["sneakers", "sport shoes", "sports shoes", "running shoes"] },
      { word: "Frantically", cls: "Adverb", def: "Done in a hurried and chaotic way.",
        keys: [["hurried", "hurry", "fast", "quickly", "rushed", "rushing", "panic", "panicky", "wild", "wildly", "frantic"], ["chaotic", "chaos", "messy", "crazy", "disorganised", "disorganized", "uncontrolled", "panic"]] },
      { word: "Severely", cls: "Adverb", def: "Very seriously.",
        keys: [["seriously", "serious", "severe", "strictly", "harshly", "badly", "strict"], ["very", "really", "extremely"]] },
      { word: "Anxious", cls: "Adjective", def: "Feeling worried and nervous.",
        keys: [["worried", "worry", "worrying", "scared", "afraid", "uneasy"], ["nervous", "nerves", "stressed", "tense", "anxiety"]] },
      { word: "Crept", cls: "Verb", def: "To move slowly, quietly and carefully.",
        keys: [["move", "moved", "walk", "walked", "go", "went", "sneak", "sneaked", "creep", "tiptoe"], ["slowly", "slow"], ["quietly", "quiet", "silently", "silent", "softly"], ["carefully", "careful", "cautiously"]],
        accept: ["sneak", "sneaked", "tiptoe", "tiptoed"] },
      { word: "Sweaty", cls: "Adjective", def: "Covered in sweat.",
        keys: [["sweat", "sweating", "sweaty", "perspiration"]] },
      { word: "Exhausting", cls: "Adjective", def: "Making you feel extremely tired.",
        keys: [["tired", "tiring", "exhausted", "sleepy", "weary"], ["extremely", "very", "really", "super", "totally", "completely"]] },
      { word: "Ancient", cls: "Adjective", def: "From a long time ago / very old.",
        keys: [["old", "ancient", "past", "history", "historic", "antique", "aged"]],
        accept: ["very old", "long ago", "a long time ago"] },
      { word: "Rival", cls: "Noun", def: "A person competing.",
        keys: [["person", "someone", "somebody", "people", "opponent", "competitor", "enemy"], ["competing", "compete", "competition", "against", "beat", "opponent", "competitor", "enemy"]] },
      { word: "Topple", cls: "Verb", def: "To lose balance and fall over.",
        keys: [["fall", "fell", "falls", "falling", "tumble", "collapse"], ["balance", "over", "down"]] },
      { word: "Hesitated", cls: "Verb", def: "To pause before you do or say something.",
        keys: [["pause", "paused", "wait", "waited", "stop", "stopped", "doubt", "doubted", "hesitate", "unsure"], ["before", "saying", "doing", "say", "do", "speak", "act", "decide"]] }
    ]
  },
  {
    id: "frans-arret-apprendre",
    title: "Arrêt Apprendre",
    deadline: "2026-09-16",   // datum van de overhoring
    subtitle: "Vocabulaire & phrases-clés",
    subject: "Frans",
    mode: "translate",
    from: "Frans",
    to: "Nederlands",
    directions: ["wd"],
    sections: { A: "In de klas", B: "Opdrachten", C: "Getallen 1 tot 20", D: "Dagen en huiswerk" },
    items: [
      { section: "A", word: "le français", def: "het Frans" },
      { section: "A", word: "le prof", def: "de docent / de leraar / de lerares / de meester" },
      { section: "A", word: "l'exercice (m)", def: "de opdracht / de oefening" },
      { section: "A", word: "oui", def: "ja" },
      { section: "A", word: "non", def: "nee" },
      { section: "A", word: "bonjour", def: "hallo, goedendag, dag, goedemorgen" },
      { section: "A", word: "au revoir", def: "tot ziens / dag / doei" },
      { section: "A", word: "très bien", def: "heel goed / zeer goed / prima" },
      { section: "A", word: "merci", def: "bedankt / dank je wel / dankjewel / dank u wel / dank je" },
      { section: "A", word: "c'est", def: "het is / dat is / dit is" },
      { section: "A", word: "Comment tu t'appelles ?", def: "Hoe heet jij? / Hoe heet je? / Wat is jouw naam?" },
      { section: "A", word: "Je m'appelle Léo.", def: "Ik heet Léo. / Mijn naam is Léo." },
      { section: "A", word: "Je ne sais pas.", def: "Ik weet het niet. / Dat weet ik niet." },
      { section: "B", word: "écoute", def: "luister / luister naar" },
      { section: "B", word: "regarde", def: "kijk naar / kijk" },
      { section: "B", word: "lis", def: "lees" },
      { section: "B", word: "écris", def: "schrijf / schrijf op" },
      { section: "B", word: "parle", def: "spreek / praat" },
      { section: "B", word: "répète", def: "herhaal / zeg na" },
      { section: "B", word: "réponds", def: "geef antwoord / antwoord" },
      { section: "B", word: "le livre", def: "het boek" },
      { section: "B", word: "l'ordinateur (m)", def: "de computer" },
      { section: "B", word: "le stylo", def: "de pen / de balpen" },
      { section: "B", word: "l'école (v)", def: "de school" },
      { section: "B", word: "prends", def: "pak, neem" },
      { section: "B", word: "ouvre", def: "open / maak open / doe open" },
      { section: "B", word: "ferme", def: "sluit / doe dicht / sluit af" },
      { section: "B", word: "cherche", def: "zoek / zoek op" },
      { section: "B", word: "choisis", def: "kies / kies uit" },
      { section: "B", word: "C'est quoi ?", def: "Wat is het? / Wat is dat?" },
      { section: "B", word: "Je ne comprends pas.", def: "Ik begrijp het niet. / Ik snap het niet." },
      { section: "B", word: "Prends le livre.", def: "Pak het boek. / Neem het boek." },
      { section: "C", word: "un", def: "één / een" },
      { section: "C", word: "deux", def: "twee" },
      { section: "C", word: "trois", def: "drie" },
      { section: "C", word: "quatre", def: "vier" },
      { section: "C", word: "cinq", def: "vijf" },
      { section: "C", word: "six", def: "zes" },
      { section: "C", word: "sept", def: "zeven" },
      { section: "C", word: "huit", def: "acht" },
      { section: "C", word: "neuf", def: "negen" },
      { section: "C", word: "dix", def: "tien" },
      { section: "C", word: "onze", def: "elf" },
      { section: "C", word: "douze", def: "twaalf" },
      { section: "C", word: "treize", def: "dertien" },
      { section: "C", word: "quatorze", def: "veertien" },
      { section: "C", word: "quinze", def: "vijftien" },
      { section: "C", word: "seize", def: "zestien" },
      { section: "C", word: "dix-sept", def: "zeventien" },
      { section: "C", word: "dix-huit", def: "achttien" },
      { section: "C", word: "dix-neuf", def: "negentien" },
      { section: "C", word: "vingt", def: "twintig" },
      { section: "D", word: "lundi", def: "maandag" },
      { section: "D", word: "mardi", def: "dinsdag" },
      { section: "D", word: "mercredi", def: "woensdag" },
      { section: "D", word: "jeudi", def: "donderdag" },
      { section: "D", word: "vendredi", def: "vrijdag" },
      { section: "D", word: "samedi", def: "zaterdag" },
      { section: "D", word: "dimanche", def: "zondag" },
      { section: "D", word: "aujourd'hui", def: "vandaag" },
      { section: "D", word: "apprends", def: "leer / leer uit je hoofd" },
      { section: "D", word: "fais", def: "doe / maak" },
      { section: "D", word: "travaille", def: "werk / werk aan" },
      { section: "D", word: "complète", def: "vul in / vul aan" },
      { section: "D", word: "les devoirs", def: "het huiswerk / de huiswerkopdrachten" },
      { section: "D", word: "le garçon", def: "de jongen" },
      { section: "D", word: "la fille", def: "het meisje / de dochter" },
      { section: "D", word: "la page", def: "de bladzijde / de pagina" },
      { section: "D", word: "le mot", def: "het woord" },
      { section: "D", word: "On a des devoirs ?", def: "Hebben we huiswerk? / Hebben wij huiswerk?" }
    ]
  }
];
